name: build_release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  build_release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'pnpm'
          pnpm-version: '10.31.0'

      - run: pnpm install

      - run: pnpm run build

      - id: version
        run: |
          version=$(node -e "import('@gkd-kit/tools').then((m) => m.stdoutGkdVersion());")
          echo "version=${version}" >> "$GITHUB_OUTPUT"

      - name: Git commit
        id: commit
        run: |
          git config --local user.email github-actions[bot]@users.noreply.github.com
          git config --local user.name github-actions[bot]
          git status
          git add -f dist/
          git commit -m "chore: v${{steps.version.outputs.version}}" || echo "nothing to commit"
        continue-on-error: true

      - name: Git push
        if: ${{ steps.commit.outcome == 'success' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

      - name: Create Release & Upload Assets
        run: |
          gh release create "v${{ steps.version.outputs.version }}" \
            --title "Release ${{ steps.version.outputs.version }}" \
            --notes-file ./dist/CHANGELOG.md \
            --latest \
            --verify-tag \
            --generate-notes \
            ./dist/gkd.json5 \
            ./dist/gkd.version.json5 || true
